"""initial tables

Revision ID: 859d395dbadd
Revises: 
Create Date: 2026-03-28 16:43:51.518537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '859d395dbadd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender'), nullable=False),
    sa.Column('ntrp', sa.Float(), nullable=False),
    sa.Column('internal_rating', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='memberstatus'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('kakao_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kakao_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=False),
    sa.Column('court_count', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('MEMBER_OPEN', 'GUEST_OPEN', 'CLOSED', name='schedulestatus'), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=50), nullable=True),
    sa.Column('parent_schedule_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('attendance_type', sa.Enum('FULL', 'LATE', 'EARLY', name='attendancetype'), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'member_id')
    )
    op.create_table('guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender'), nullable=False),
    sa.Column('estimated_skill', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='guestskill'), nullable=False),
    sa.Column('registered_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchmakings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', name='matchmakingstatus'), nullable=False),
    sa.Column('constraints', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matchmaking_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matchmaking_id'], ['matchmakings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('court', sa.String(length=5), nullable=False),
    sa.Column('team_a_player1_id', sa.UUID(), nullable=False),
    sa.Column('team_a_player2_id', sa.UUID(), nullable=False),
    sa.Column('team_b_player1_id', sa.UUID(), nullable=False),
    sa.Column('team_b_player2_id', sa.UUID(), nullable=False),
    sa.Column('team_a_player1_type', sa.Enum('MEMBER', 'GUEST', name='playertype'), nullable=False),
    sa.Column('team_a_player2_type', sa.Enum('MEMBER', 'GUEST', name='playertype'), nullable=False),
    sa.Column('team_b_player1_type', sa.Enum('MEMBER', 'GUEST', name='playertype'), nullable=False),
    sa.Column('team_b_player2_type', sa.Enum('MEMBER', 'GUEST', name='playertype'), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['match_rounds.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('match_rounds')
    op.drop_table('matchmakings')
    op.drop_table('guests')
    op.drop_table('attendances')
    op.drop_table('schedules')
    op.drop_table('members')
    # ### end Alembic commands ###
